from BaseLayer import BaseLayer

class LinearLayer(BaseLayer): ...

class ELULayer(BaseLayer): ...

class ReLULayer(BaseLayer): ...

class LeakyReLULayer(BaseLayer): ...

class SigmoidLayer(BaseLayer): ...

class TanhLayer(BaseLayer): ...

class SoftmaxLayer(BaseLayer): ...